
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class frmCiv
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView nvCiudades;
		
		private global::Gtk.HButtonBox hbuttonbox1;
		
		private global::Gtk.Button cmdIrCiudad;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.NodeView nvAvances;
		
		private global::Gtk.Label GtkLabel1;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.NodeView nvInvestigando;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.NodeView nvInvestDetalle;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.VBox vbox3;
		
		private global::gtk.wgArmadaComboBox ArmadaSelector;
		
		private global::gtk.ArmadaWidget ArmadaSeleccionadaInfo;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Expander expIr;
		
		private global::Gtk.HBox hbox5;
		
		private global::gtk.GeneralCombobox IrACB;
		
		private global::Gtk.Button cmdIrA;
		
		private global::Gtk.Label GtkLabel9;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Statusbar statusbar;
		
		private global::gtk.MensView Mens;
		
		private global::Gtk.Button cmdActualiza;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtk.frmCiv
			this.Name = "gtk.frmCiv";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmCiv");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child gtk.frmCiv.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nvCiudades = new global::Gtk.NodeView ();
			this.nvCiudades.CanFocus = true;
			this.nvCiudades.Name = "nvCiudades";
			this.GtkScrolledWindow.Add (this.nvCiudades);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.cmdIrCiudad = new global::Gtk.Button ();
			this.cmdIrCiudad.CanFocus = true;
			this.cmdIrCiudad.Name = "cmdIrCiudad";
			this.cmdIrCiudad.UseUnderline = true;
			this.cmdIrCiudad.Label = global::Mono.Unix.Catalog.GetString ("_Ir a");
			this.hbuttonbox1.Add (this.cmdIrCiudad);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.cmdIrCiudad]));
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.notebook1.Add (this.vbox2);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Ciudades");
			this.notebook1.SetTabLabel (this.vbox2, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame1.LabelXalign = 1F;
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.WidthRequest = 0;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nvAvances = new global::Gtk.NodeView ();
			this.nvAvances.WidthRequest = 200;
			this.nvAvances.CanFocus = true;
			this.nvAvances.Name = "nvAvances";
			this.GtkScrolledWindow1.Add (this.nvAvances);
			this.GtkAlignment.Add (this.GtkScrolledWindow1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Avances</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.hbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame2.LabelXalign = 1F;
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.nvInvestigando = new global::Gtk.NodeView ();
			this.nvInvestigando.WidthRequest = 200;
			this.nvInvestigando.CanFocus = true;
			this.nvInvestigando.Name = "nvInvestigando";
			this.GtkScrolledWindow3.Add (this.nvInvestigando);
			this.hbox3.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow3]));
			w11.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nvInvestDetalle = new global::Gtk.NodeView ();
			this.nvInvestDetalle.WidthRequest = 400;
			this.nvInvestDetalle.CanFocus = true;
			this.nvInvestDetalle.Name = "nvInvestDetalle";
			this.GtkScrolledWindow2.Add (this.nvInvestDetalle);
			this.hbox3.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow2]));
			w13.Position = 1;
			this.GtkAlignment1.Add (this.hbox3);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Investigando</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel2;
			this.hbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame2]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.notebook1.Add (this.hbox1);
			global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox1]));
			w17.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("_Avances");
			this.label2.UseUnderline = true;
			this.notebook1.SetTabLabel (this.hbox1, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.ArmadaSelector = new global::gtk.wgArmadaComboBox ();
			this.ArmadaSelector.Events = ((global::Gdk.EventMask)(256));
			this.ArmadaSelector.Name = "ArmadaSelector";
			this.vbox3.Add (this.ArmadaSelector);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.ArmadaSelector]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.ArmadaSeleccionadaInfo = new global::gtk.ArmadaWidget ();
			this.ArmadaSeleccionadaInfo.WidthRequest = 200;
			this.ArmadaSeleccionadaInfo.Events = ((global::Gdk.EventMask)(256));
			this.ArmadaSeleccionadaInfo.Name = "ArmadaSeleccionadaInfo";
			this.vbox3.Add (this.ArmadaSeleccionadaInfo);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.ArmadaSeleccionadaInfo]));
			w19.Position = 1;
			this.hbox4.Add (this.vbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.expIr = new global::Gtk.Expander (null);
			this.expIr.CanFocus = true;
			this.expIr.Name = "expIr";
			this.expIr.Expanded = true;
			// Container child expIr.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.IrACB = new global::gtk.GeneralCombobox ();
			this.IrACB.Events = ((global::Gdk.EventMask)(256));
			this.IrACB.Name = "IrACB";
			this.hbox5.Add (this.IrACB);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.IrACB]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.cmdIrA = new global::Gtk.Button ();
			this.cmdIrA.CanFocus = true;
			this.cmdIrA.Name = "cmdIrA";
			this.cmdIrA.UseUnderline = true;
			this.cmdIrA.Label = global::Mono.Unix.Catalog.GetString ("_Ir");
			this.hbox5.Add (this.cmdIrA);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.cmdIrA]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.expIr.Add (this.hbox5);
			this.GtkLabel9 = new global::Gtk.Label ();
			this.GtkLabel9.Name = "GtkLabel9";
			this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("Ir a");
			this.GtkLabel9.UseUnderline = true;
			this.expIr.LabelWidget = this.GtkLabel9;
			this.vbox4.Add (this.expIr);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.expIr]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox4.Add (this.vbox4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox4]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.notebook1.Add (this.hbox4);
			global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox4]));
			w26.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Armadas");
			this.notebook1.SetTabLabel (this.hbox4, this.label3);
			this.label3.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w27.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar = new global::Gtk.Statusbar ();
			this.statusbar.Name = "statusbar";
			this.statusbar.Spacing = 6;
			// Container child statusbar.Gtk.Box+BoxChild
			this.Mens = new global::gtk.MensView ();
			this.Mens.Events = ((global::Gdk.EventMask)(256));
			this.Mens.Name = "Mens";
			this.statusbar.Add (this.Mens);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.Mens]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child statusbar.Gtk.Box+BoxChild
			this.cmdActualiza = new global::Gtk.Button ();
			this.cmdActualiza.CanFocus = true;
			this.cmdActualiza.Name = "cmdActualiza";
			this.cmdActualiza.UseUnderline = true;
			this.cmdActualiza.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.statusbar.Add (this.cmdActualiza);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.cmdActualiza]));
			w29.PackType = ((global::Gtk.PackType)(1));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox1.Add (this.statusbar);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1002;
			this.DefaultHeight = 300;
			this.Show ();
			this.cmdIrCiudad.Activated += new global::System.EventHandler (this.OnCmdIrActivated);
			this.cmdIrCiudad.Clicked += new global::System.EventHandler (this.OnCmdIrActivated);
			this.nvInvestigando.CursorChanged += new global::System.EventHandler (this.OnNvInvestigandoCursorChanged);
			this.ArmadaSelector.onSelectionChanged += new global::System.EventHandler (this.OnArmadaSelectoronSelectionChanged);
			this.cmdIrA.Clicked += new global::System.EventHandler (this.OnCmdIrAClicked);
			this.cmdIrA.Activated += new global::System.EventHandler (this.OnCmdIrAClicked);
			this.cmdActualiza.Clicked += new global::System.EventHandler (this.OnCmdActualizaClicked);
			this.cmdActualiza.Activated += new global::System.EventHandler (this.OnCmdActualizaClicked);
		}
	}
}
