
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class MensView
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button cmdBorrar;
		
		private global::Gtk.Label label;
		
		private global::Gtk.Button cmdAtras;
		
		private global::Gtk.Button cmdAdel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtk.MensView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "gtk.MensView";
			// Container child gtk.MensView.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdBorrar = new global::Gtk.Button ();
			this.cmdBorrar.Sensitive = false;
			this.cmdBorrar.CanFocus = true;
			this.cmdBorrar.Name = "cmdBorrar";
			this.cmdBorrar.UseStock = true;
			this.cmdBorrar.UseUnderline = true;
			this.cmdBorrar.Label = "gtk-remove";
			this.hbox1.Add (this.cmdBorrar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdBorrar]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.Xalign = 0F;
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("label");
			this.hbox1.Add (this.label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdAtras = new global::Gtk.Button ();
			this.cmdAtras.Sensitive = false;
			this.cmdAtras.CanFocus = true;
			this.cmdAtras.Name = "cmdAtras";
			this.cmdAtras.UseStock = true;
			this.cmdAtras.UseUnderline = true;
			this.cmdAtras.Label = "gtk-go-back";
			this.hbox1.Add (this.cmdAtras);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdAtras]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdAdel = new global::Gtk.Button ();
			this.cmdAdel.Sensitive = false;
			this.cmdAdel.CanFocus = true;
			this.cmdAdel.Name = "cmdAdel";
			this.cmdAdel.UseStock = true;
			this.cmdAdel.UseUnderline = true;
			this.cmdAdel.Label = "gtk-go-forward";
			this.hbox1.Add (this.cmdAdel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdAdel]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.cmdBorrar.Clicked += new global::System.EventHandler (this.OnCmdBorrarClicked);
			this.cmdBorrar.Activated += new global::System.EventHandler (this.OnCmdBorrarClicked);
			this.cmdAtras.Clicked += new global::System.EventHandler (this.OnButton19Clicked);
			this.cmdAtras.Activated += new global::System.EventHandler (this.OnButton19Clicked);
			this.cmdAdel.Clicked += new global::System.EventHandler (this.OnCmdAdelClicked);
			this.cmdAdel.Activated += new global::System.EventHandler (this.OnCmdAdelClicked);
		}
	}
}
