
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class wgArmadaComboBox
	{
		private global::Gtk.ComboBox comboBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtk.wgArmadaComboBox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "gtk.wgArmadaComboBox";
			// Container child gtk.wgArmadaComboBox.Gtk.Container+ContainerChild
			this.comboBox = global::Gtk.ComboBox.NewText ();
			this.comboBox.Name = "comboBox";
			this.Add (this.comboBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.comboBox.Changed += new global::System.EventHandler (this.OnComboBoxChanged);
		}
	}
}
