
// This file has been generated by the GUI designer. Do not modify.
namespace Gtk
{
	public partial class MensView
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button cmdBorrar;
		
		private global::Gtk.Label label;
		
		private global::Gtk.Button cmdAtras;
		
		private global::Gtk.Button cmdAdel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtk.MensView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "gtk.MensView";
			// Container child gtk.MensView.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdBorrar = new global::Gtk.Button ();
			this.cmdBorrar.Sensitive = false;
			this.cmdBorrar.CanFocus = true;
			this.cmdBorrar.Name = "cmdBorrar";
			this.cmdBorrar.UseUnderline = true;
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Button);
			this.cmdBorrar.Image = w1;
			this.hbox1.Add (this.cmdBorrar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdBorrar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.Xalign = 0F;
			this.label.MaxWidthChars = 200;
			this.hbox1.Add (this.label);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdAtras = new global::Gtk.Button ();
			this.cmdAtras.Sensitive = false;
			this.cmdAtras.CanFocus = true;
			this.cmdAtras.Name = "cmdAtras";
			this.cmdAtras.UseUnderline = true;
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.cmdAtras.Image = w4;
			this.hbox1.Add (this.cmdAtras);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdAtras]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdAdel = new global::Gtk.Button ();
			this.cmdAdel.Sensitive = false;
			this.cmdAdel.CanFocus = true;
			this.cmdAdel.Name = "cmdAdel";
			this.cmdAdel.UseUnderline = true;
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.cmdAdel.Image = w6;
			this.hbox1.Add (this.cmdAdel);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdAdel]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.cmdBorrar.Clicked += new global::System.EventHandler (this.OnCmdBorrarClicked);
			this.cmdBorrar.Activated += new global::System.EventHandler (this.OnCmdBorrarClicked);
			this.cmdAtras.Clicked += new global::System.EventHandler (this.OnButton19Clicked);
			this.cmdAtras.Activated += new global::System.EventHandler (this.OnButton19Clicked);
			this.cmdAdel.Clicked += new global::System.EventHandler (this.OnCmdAdelClicked);
			this.cmdAdel.Activated += new global::System.EventHandler (this.OnCmdAdelClicked);
		}
	}
}
