
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class frmCiudad
	{
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label lbCityInfo;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.NodeView nvTrabajos;
		
		private global::Gtk.HButtonBox hbuttonbox1;
		
		private global::Gtk.Button cmdRenombrarCiudad;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.NodeView nvRecursos;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtk.frmCiudad
			this.Name = "gtk.frmCiudad";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmCiudad");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child gtk.frmCiudad.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.HeightRequest = 300;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lbCityInfo = new global::Gtk.Label ();
			this.lbCityInfo.Name = "lbCityInfo";
			this.lbCityInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.hbox1.Add (this.lbCityInfo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lbCityInfo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nvTrabajos = new global::Gtk.NodeView ();
			this.nvTrabajos.WidthRequest = 600;
			this.nvTrabajos.CanFocus = true;
			this.nvTrabajos.Name = "nvTrabajos";
			this.GtkScrolledWindow2.Add (this.nvTrabajos);
			this.hbox1.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow2]));
			w3.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.BorderWidth = ((uint)(9));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.cmdRenombrarCiudad = new global::Gtk.Button ();
			this.cmdRenombrarCiudad.CanFocus = true;
			this.cmdRenombrarCiudad.Name = "cmdRenombrarCiudad";
			this.cmdRenombrarCiudad.UseUnderline = true;
			this.cmdRenombrarCiudad.Label = global::Mono.Unix.Catalog.GetString ("_Renombrar");
			this.hbuttonbox1.Add (this.cmdRenombrarCiudad);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.cmdRenombrarCiudad]));
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.notebook1.Add (this.vbox1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.notebook1.SetTabLabel (this.vbox1, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nvRecursos = new global::Gtk.NodeView ();
			this.nvRecursos.CanFocus = true;
			this.nvRecursos.Name = "nvRecursos";
			this.GtkScrolledWindow1.Add (this.nvRecursos);
			this.notebook1.Add (this.GtkScrolledWindow1);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow1]));
			w9.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Recursos");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow1, this.label2);
			this.label2.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 665;
			this.DefaultHeight = 380;
			this.Show ();
		}
	}
}
