
// This file has been generated by the GUI designer. Do not modify.
namespace Gtk
{
	public partial class ReclutarWidget
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView Nodeview;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtk.ReclutarWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Gtk.ReclutarWidget";
			// Container child Gtk.ReclutarWidget.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.Nodeview = new global::Gtk.NodeView ();
			this.Nodeview.CanFocus = true;
			this.Nodeview.Name = "Nodeview";
			this.GtkScrolledWindow.Add (this.Nodeview);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
