
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class wgArmadaComboBox
	{
		private global::Gtk.ComboBox combobox3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtk.wgArmadaComboBox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "gtk.wgArmadaComboBox";
			// Container child gtk.wgArmadaComboBox.Gtk.Container+ContainerChild
			this.combobox3 = global::Gtk.ComboBox.NewText ();
			this.combobox3.Name = "combobox3";
			this.Add (this.combobox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
