
// This file has been generated by the GUI designer. Do not modify.
namespace Gtk
{
	public partial class GeneralCombobox
	{
		private global::Gtk.ComboBox combobox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtk.GeneralCombobox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Gtk.GeneralCombobox";
			// Container child Gtk.GeneralCombobox.Gtk.Container+ContainerChild
			this.combobox = global::Gtk.ComboBox.NewText ();
			this.combobox.Name = "combobox";
			this.Add (this.combobox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
