
// This file has been generated by the GUI designer. Do not modify.
namespace Gtk
{
	public partial class FrmCiudad
	{
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private Gtk.PopDisplay popdisplay1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.NodeView nvTrabajos;
		
		private global::Gtk.HButtonBox hbuttonbox1;
		
		private global::Gtk.Button cmdRenombrarCiudad;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.NodeView nvRecursos;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.HBox hbox4;
		
		private Gtk.ArmadaWidget armDefensa;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox5;
		
		private Gtk.ArmadaComboBoxWidget ArmadaCombobox;
		
		private global::Gtk.Button cmdAddArmada;
		
		private global::Gtk.Frame fEdiciónArmada;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.VBox vbox4;
		
		private Gtk.ArmadaWidget armSeleccionada;
		
		private global::Gtk.HButtonBox btboxEditArmada;
		
		private global::Gtk.Button cmdAdd;
		
		private global::Gtk.Label GtkLabel3;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private Gtk.ReclutarWidget rcReclutar;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Label label7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtk.frmCiudad
			this.Name = "gtk.frmCiudad";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmCiudad");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child gtk.frmCiudad.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.HeightRequest = 300;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.popdisplay1 = new Gtk.PopDisplay ();
			this.popdisplay1.Events = ((global::Gdk.EventMask)(256));
			this.popdisplay1.Name = "popdisplay1";
			this.hbox1.Add (this.popdisplay1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.popdisplay1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nvTrabajos = new global::Gtk.NodeView ();
			this.nvTrabajos.WidthRequest = 600;
			this.nvTrabajos.CanFocus = true;
			this.nvTrabajos.Name = "nvTrabajos";
			this.GtkScrolledWindow2.Add (this.nvTrabajos);
			this.hbox1.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow2]));
			w3.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.BorderWidth = ((uint)(9));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.cmdRenombrarCiudad = new global::Gtk.Button ();
			this.cmdRenombrarCiudad.CanFocus = true;
			this.cmdRenombrarCiudad.Name = "cmdRenombrarCiudad";
			this.cmdRenombrarCiudad.UseUnderline = true;
			this.cmdRenombrarCiudad.Label = global::Mono.Unix.Catalog.GetString ("_Renombrar");
			this.hbuttonbox1.Add (this.cmdRenombrarCiudad);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.cmdRenombrarCiudad]));
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.notebook1.Add (this.vbox1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.notebook1.SetTabLabel (this.vbox1, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nvRecursos = new global::Gtk.NodeView ();
			this.nvRecursos.CanFocus = true;
			this.nvRecursos.Name = "nvRecursos";
			this.GtkScrolledWindow1.Add (this.nvRecursos);
			this.notebook1.Add (this.GtkScrolledWindow1);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow1]));
			w9.Position = 1;
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Recursos");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow1, this.label6);
			this.label6.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.armDefensa = new Gtk.ArmadaWidget ();
			this.armDefensa.Events = ((global::Gdk.EventMask)(256));
			this.armDefensa.Name = "armDefensa";
			this.hbox4.Add (this.armDefensa);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.armDefensa]));
			w10.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.ArmadaCombobox = new Gtk.ArmadaComboBoxWidget ();
			this.ArmadaCombobox.Events = ((global::Gdk.EventMask)(256));
			this.ArmadaCombobox.Name = "ArmadaCombobox";
			this.hbox5.Add (this.ArmadaCombobox);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.ArmadaCombobox]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.cmdAddArmada = new global::Gtk.Button ();
			this.cmdAddArmada.CanFocus = true;
			this.cmdAddArmada.Name = "cmdAddArmada";
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (
				this,
				"gtk-add",
				global::Gtk.IconSize.Menu);
			this.cmdAddArmada.Image = w12;
			this.hbox5.Add (this.cmdAddArmada);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.cmdAddArmada]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fEdiciónArmada = new global::Gtk.Frame ();
			this.fEdiciónArmada.Name = "fEdiciónArmada";
			this.fEdiciónArmada.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child fEdiciónArmada.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.armSeleccionada = new Gtk.ArmadaWidget ();
			this.armSeleccionada.Events = ((global::Gdk.EventMask)(256));
			this.armSeleccionada.Name = "armSeleccionada";
			this.vbox4.Add (this.armSeleccionada);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.armSeleccionada]));
			w15.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btboxEditArmada = new global::Gtk.HButtonBox ();
			this.btboxEditArmada.Name = "btboxEditArmada";
			// Container child btboxEditArmada.Gtk.ButtonBox+ButtonBoxChild
			this.cmdAdd = new global::Gtk.Button ();
			this.cmdAdd.CanFocus = true;
			this.cmdAdd.Name = "cmdAdd";
			this.cmdAdd.UseUnderline = true;
			this.cmdAdd.Label = global::Mono.Unix.Catalog.GetString ("_A armada");
			global::Gtk.Image w16 = new global::Gtk.Image ();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (
				this,
				"stock_right",
				global::Gtk.IconSize.SmallToolbar);
			this.cmdAdd.Image = w16;
			this.btboxEditArmada.Add (this.cmdAdd);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.btboxEditArmada [this.cmdAdd]));
			w17.Expand = false;
			w17.Fill = false;
			this.vbox4.Add (this.btboxEditArmada);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btboxEditArmada]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.GtkAlignment2.Add (this.vbox4);
			this.fEdiciónArmada.Add (this.GtkAlignment2);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Armada</b>");
			this.GtkLabel3.UseMarkup = true;
			this.fEdiciónArmada.LabelWidget = this.GtkLabel3;
			this.vbox3.Add (this.fEdiciónArmada);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fEdiciónArmada]));
			w21.Position = 1;
			this.hbox4.Add (this.vbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.WidthRequest = 300;
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.rcReclutar = new Gtk.ReclutarWidget ();
			this.rcReclutar.Events = ((global::Gdk.EventMask)(256));
			this.rcReclutar.Name = "rcReclutar";
			this.GtkAlignment1.Add (this.rcReclutar);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>_Reclutar</b>");
			this.GtkLabel2.UseMarkup = true;
			this.GtkLabel2.UseUnderline = true;
			this.frame2.LabelWidget = this.GtkLabel2;
			this.hbox4.Add (this.frame2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame2]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.notebook1.Add (this.hbox4);
			global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox4]));
			w26.Position = 2;
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("_Armada");
			this.label7.UseUnderline = true;
			this.notebook1.SetTabLabel (this.hbox4, this.label7);
			this.label7.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null))
			{
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 724;
			this.DefaultHeight = 380;
			this.Show ();
			this.notebook1.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnNotebook1SwitchPage);
			this.ArmadaCombobox.OnSelectionChanged += new global::System.EventHandler (this.OnArmadaComboboxonSelectionChanged);
			this.cmdAddArmada.Clicked += new global::System.EventHandler (this.OnCmdAddArmadaClicked);
			this.cmdAdd.Clicked += new global::System.EventHandler (this.OnCmdAddClicked);
		}
	}
}
