
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class ArmadaWidget
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView TreeView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget gtk.ArmadaWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "gtk.ArmadaWidget";
			// Container child gtk.ArmadaWidget.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TreeView = new global::Gtk.TreeView ();
			this.TreeView.CanFocus = true;
			this.TreeView.Name = "TreeView";
			this.GtkScrolledWindow.Add (this.TreeView);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
