
// This file has been generated by the GUI designer. Do not modify.
public partial class CivWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HButtonBox hbuttonbox1;
	private global::Gtk.Button cmdTurno;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::MonoDevelop.Components.ListView lvInfo;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget CivWindow
		this.Name = "CivWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Civilización");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child CivWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.cmdTurno = new global::Gtk.Button ();
		this.cmdTurno.CanFocus = true;
		this.cmdTurno.Name = "cmdTurno";
		this.cmdTurno.UseUnderline = true;
		// Container child cmdTurno.Gtk.Container+ContainerChild
		global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w2 = new global::Gtk.HBox ();
		w2.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w3 = new global::Gtk.Image ();
		w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.SmallToolbar);
		w2.Add (w3);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w5 = new global::Gtk.Label ();
		w5.LabelProp = global::Mono.Unix.Catalog.GetString ("_Turno");
		w5.UseUnderline = true;
		w2.Add (w5);
		w1.Add (w2);
		this.cmdTurno.Add (w1);
		this.hbuttonbox1.Add (this.cmdTurno);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.cmdTurno]));
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w11 = new global::Gtk.Viewport ();
		w11.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.lvInfo = new global::MonoDevelop.Components.ListView ();
		this.lvInfo.Name = "lvInfo";
		this.lvInfo.AllowMultipleSelection = false;
		this.lvInfo.SelectedRow = 0;
		this.lvInfo.SelectionDisabled = false;
		this.lvInfo.Page = 0;
		w11.Add (this.lvInfo);
		this.GtkScrolledWindow.Add (w11);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w14.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
